services:
  database:
      image: postgres:15-alpine
      container_name: fleet_db
      env_file:
        - .env.docker
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local